server:
  port: 8082

spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_customer
    username: postgres
    password: asmaa123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 